# Generated by Django 5.2.4 on 2025-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
