# Generated by Django 5.2.4 on 2025-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_portfolio_project_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
