# Generated by Django 5.2.4 on 2025-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_professionalskill_rename_skill_technicalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalskill',
            name='icon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
