# Generated by Django 5.2.4 on 2025-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_education_description_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_image',
            field=models.ImageField(default=1, upload_to='education_images/'),
            preserve_default=False,
        ),
    ]
