# Generated by Django 5.2.4 on 2025-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.ManyToManyField(blank=True, to='index.tools'),
        ),
    ]
