# Generated by Django 5.2.4 on 2025-08-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_project_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
