# Generated by Django 5.2.4 on 2025-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_portfolio_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
