# Generated by Django 5.2.4 on 2025-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_contactdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
