# Generated by Django 5.2.4 on 2025-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_contactdetails_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='footer_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
