# Generated by Django 5.2.4 on 2025-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_portfolio_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
