# Generated by Django 5.2.4 on 2025-08-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='stackoverflow',
            field=models.URLField(blank=True, null=True),
        ),
    ]
