# Generated by Django 5.2.4 on 2025-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_sociallink_stackoverflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
