# Generated by Django 5.2.4 on 2025-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_portfolio_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
